general:
  project_name: handposture

dataset:
  name: ST_VL53L5CX_handposture_dataset
  class_names: [None, Like, Dislike, FlatHand, Fist, Love, BreakTime, CrossHands]
  test_path:  /opt/ml/processing/input/datasets/ST_VL53L5CX_handposture_dataset
    
   
pre_processing:
  Max_distance: 500
  Min_distance: 100
  Background_distance: 120


model:
  model_type: {name : CNN2D_ST_HandPosture, version : v1}
  input_shape: [8, 8, 2]
  model_path: ../../models/CNN2D_ST_HandPosture/ST_pretrainedmodel_custom_dataset/ST_VL53L5CX_handposture_dataset/CNN2D_ST_HandPosture_8classes/CNN2D_ST_HandPosture_8classes.h5
  dropout: 0.4

stm32ai:
  version: 8.1.0
  serie: STM32U5
  IDE: GCC
  verbosity: 1
  path_to_stm32ai: C:/STMicroelectronics/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/8.1.0/Utilities/windows/stm32ai.exe
  optimization: balanced
  footprints_on_target: B-U585I-IOT02A
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: /opt/ml/processing/outputs/build
